# Generated by Django 3.1.5 on 2021-03-02 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20210302_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('discount_amount', 0), ('discount_percentage__gt', 0), ('discount_percentage__lte', 100)), models.Q(('discount_percentage', 0), ('discount_amount__gt', 0)), _connector='OR'), name='only_one_discount'),
        ),
    ]
