# Generated by Django 3.1.5 on 2021-03-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20210302_0925'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coupon',
            name='only_one_discount',
        ),
    ]
