# Generated by Django 3.1.5 on 2021-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20210302_0937'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('discount_amount', 0), ('discount_percentage__gt', 0), ('discount_percentage__lte', 100)), models.Q(('discount_percentage', 0), ('discount_amount__gt', 0)), _connector='OR'), name='only_one_discount'),
        ),
    ]
