# Generated by Django 3.1.5 on 2021-03-02 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20210302_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='stock',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coupons restant'),
        ),
    ]
