# Generated by Django 3.1.5 on 2021-02-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='Wilaya',
            new_name='wilaya',
        ),
    ]
