# Generated by Django 3.1.5 on 2021-02-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_auto_20210204_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoutLivraison',
        ),
    ]
