# Generated by Django 3.1.5 on 2021-02-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_delete_coutlivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='cout',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10),
            preserve_default=False,
        ),
    ]
