# Generated by Django 3.1.5 on 2021-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0006_auto_20210209_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='cout',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût de Livraison'),
        ),
    ]
