# Generated by Django 3.1.5 on 2021-04-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_auto_20210303_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='Wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.wilaya', verbose_name='Wilaya'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom Commune'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='activer',
            field=models.BooleanField(default=True, verbose_name='Activer'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom Wilaya'),
        ),
    ]
