# Generated by Django 3.1.5 on 2021-04-29 12:42

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0008_auto_20210429_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='name',
        ),
        migrations.CreateModel(
            name='WilayaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=30, verbose_name='Nom Wilaya')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='livraison.wilaya')),
            ],
            options={
                'verbose_name': 'wilaya Translation',
                'db_table': 'livraison_wilaya_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='CommuneTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=30, verbose_name='Nom Commune')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='livraison.commune')),
            ],
            options={
                'verbose_name': 'commune Translation',
                'db_table': 'livraison_commune_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
