# Generated by Django 3.1.5 on 2021-01-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=7)),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='SubCateory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('CH', 'chaussures'), ('SA', 'sacs'), ('AC', 'accessoires')], default='CH', max_length=2)),
            ],
            options={
                'verbose_name': 'Sous Catégorie',
                'verbose_name_plural': 'sous Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('livraison', models.IntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Photo Principale')),
                ('status', models.CharField(blank=True, choices=[('N', 'nouveau'), ('R', 'rupture'), ('P', 'promotion'), ('S', 'SANS')], default='N', max_length=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('description', models.TextField(blank=True)),
                ('afficher', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.ManyToManyField(to='main.Color')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcateory', verbose_name='sous categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wilaya')),
            ],
        ),
    ]
