# Generated by Django 3.1.5 on 2021-01-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210122_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcateory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='main.category', verbose_name='categorie'),
        ),
    ]
