# Generated by Django 3.1.5 on 2021-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210122_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='nom')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Photo Secondaire'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Photo Térciaire'),
        ),
        migrations.AddField(
            model_name='product',
            name='taille',
            field=models.ManyToManyField(to='main.Taille'),
        ),
    ]
