# Generated by Django 3.1.5 on 2021-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210207_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.ManyToManyField(to='main.Taille'),
        ),
    ]
