# Generated by Django 3.1.5 on 2021-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210408_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Produit'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nom catégorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom commune'),
        ),
        migrations.AlterField(
            model_name='product',
            name='afficher',
            field=models.BooleanField(default=True, verbose_name='Afficher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='main.Color', verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CRÉE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_home',
            field=models.BooleanField(default=True, verbose_name="Afficher dans l'accueil"),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Nouveau'), ('R', 'Rupture'), ('P', 'Promotion'), ('S', 'SANS')], default='N', max_length=1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.ManyToManyField(to='main.Taille', verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFIÉ'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='livraison',
            field=models.IntegerField(default=0, verbose_name='Prix livraison'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom wilaya'),
        ),
    ]
