# Generated by Django 3.1.5 on 2021-04-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='subcateory',
            options={'verbose_name': 'Sous Catégorie', 'verbose_name_plural': 'Sous Catégories'},
        ),
        migrations.AlterField(
            model_name='commune',
            name='Wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wilaya', verbose_name='Wilaya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='subcateory',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nom Sous Catégorie'),
        ),
        migrations.AlterField(
            model_name='subcateory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug Catégorie'),
        ),
    ]
