# Generated by Django 3.1.5 on 2021-01-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adresse',
            new_name='addresse',
        ),
    ]
