# Generated by Django 3.1.5 on 2021-01-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
        ('orders', '0003_auto_20210121_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.commune'),
        ),
        migrations.AddField(
            model_name='order',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.wilaya'),
        ),
    ]
