# Generated by Django 3.1.5 on 2021-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210207_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Confirmer',
            field=models.BooleanField(default=False),
        ),
    ]
