# Generated by Django 3.1.5 on 2021-02-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_confirmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Confirmer',
            new_name='confirmer',
        ),
    ]
